<?php
// @codingStandardsIgnoreFile

?>
<div class="actions">
    <?php  $order = $block->getOrder() ?>
        <?php if ($this->helper('Magento\Sales\Helper\Reorder')->canReorder($order->getEntityId())) : ?>
            <a
                class="action order"
                href="#"
                data-post='<?php /* @escapeNotVerified */ echo $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)->getPostData($block->getReorderUrl($order)) ?>'
            >
                <span><?php /* @escapeNotVerified */ echo __('Reorder') ?></span>
            </a>
        <?php endif ?>
        <?php if ($this->helper(\MageSuite\Frontend\Helper\Order::class)->canPrintOrder()) : ?>
            <a
                class="action print"
                href="<?php /* @escapeNotVerified */ echo $block->getPrintUrl($order) ?>"
                onclick="this.target='_blank';"
            >
                <span><?php /* @escapeNotVerified */ echo __('Print Order') ?></span>
            </a>
        <?php endif ?>

    <?php echo $block->getChildHtml(); ?>
</div>
